### ISSUE TITLE
Error uploading files when using a port on the URL

### ISSUE THREAD

**Issue by laraning** [froala/nova-froala-field#10]
Hi,

Great work first of all! Congratulations!

The issue is simple: If I use a port on the url, on my case "localhost:8000" the "link" value on the returned ajax json called from the "nova-vendor/froala-field/posts/attachments/body" doesn't show the url.

Steps to reproduce:

Start a webserver with a port. You can use the default 8000 when running "php artisan serve".

Try to upload an image:
![image](https://user-images.githubusercontent.com/35408392/50863659-ade98180-139f-11e9-994f-39feb4badb4e.png)

Then you can see the "link" value is wrong:
![image](https://user-images.githubusercontent.com/35408392/50863688-c5c10580-139f-11e9-8780-7209a3e52222.png)

I dug up the code and the StorePendingAttachment class looks like it's working correctly. Still, the line:
Storage::disk($this->field->disk)->url($attachment)
is not showing the right url somehow ... 

Hope it helps!
Bruno.

**Comment by slavarazum** [comment]
Hi. Thanks for the feedback!

Did you setup a `url` option in your *filesystem* config correctly?

Like this: `'url' => env('APP_URL').'/storage'`

**Comment by laraning** [comment]
You're right, sorry for that.

the url() methods fetches the app.url configuration parameter and not a dynamically constructed given the url passed in the browser. Sorry, my mistake, thanks for the help!

Bruno

**Comment by slavarazum** [comment]
You are welcome
