### ISSUE TITLE
translatable compatibility

### ISSUE THREAD

**Issue by thanoseleftherakos** [froala/nova-froala-field#11]
I've tried froala field with spatie/laravel-translatable but it seems that its not compatible.
The error im getting is "Unknown column translations_content_en in field list"
Any plans to support this package?

**Comment by slavarazum** [comment]
Could you please clarify, when and why you got this error? Nova Froala Field works with any text field of Eloquent model.

**Comment by thanoseleftherakos** [comment]
Im using the above code in my nova model fields.
When I try to edit the model im getting the sql error that I've posted above.
```
public function fields(Request $request)
{
    return [
        Translatable::make([ 
            Froala::make('Content')
        ]);
    ]
}
```
If I use the Trix editor it works as expected.

**Comment by slavarazum** [comment]
Haven't experienced `spatie/laravel-translatable`. Feel free to fix this issue and send a PR to `master` branch.
