### ISSUE TITLE
No Issue

### ISSUE THREAD

**Issue by astr0naugh7** [froala/nova-froala-field#12]
No issue, I just want to say I LOVE this and it's been working amazingly for me. Please keep up the amazing work and thank you. Sorry, just didn't know where else I could post this. Best Nova package ever!

**Comment by slavarazum** [comment]
Really appreciate your feedback! Happy that you enjoy it.
It's very important to hear, thanks and welcome!

**Comment by oluwatosinolamilekan** [comment]
is it only laravel nova we can use it for  because i want to integrate the text editor to a project on mine
