### ISSUE TITLE
Froala fields not displaying on index

### ISSUE THREAD

**Issue by JoshReading** [froala/nova-froala-field#2]
Hi

I have the following code

```
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Froala::make('Question')->withFiles('public')->sortable(),
            Froala::make('Answer')->withFiles('public')
        ];
    }
```

Which works fine when adding or editing a resource, but when i go to the index view of the resource i only get the ID and not the Question/Answer text displayed in the table

If i switch from Froala to a standard Text::make it then works and displays on the resource group index

Anyone have any ideas?

![screenshot 2018-11-14 at 17 29 40](https://user-images.githubusercontent.com/1227552/48500492-e69f2b80-e832-11e8-9fa3-55813f3ae00a.png)
![screenshot 2018-11-14 at 17 29 35](https://user-images.githubusercontent.com/1227552/48500493-e69f2b80-e832-11e8-98f0-81b8f38be528.png)

**Comment by slavarazum** [comment]
Hi @JoshReading

Field doesn't show on index page by default.

You should use `showOnIndex()` method to enable this behavior.
Check out the documentation - https://github.com/froala/nova-froala-field/blob/master/README.md#show-on-index-page

**Comment by JoshReading** [comment]
@slavarazum sorry didn't spot that - thanks!

Although for every field it just displays 'Show Content' which when clicked gives a popup, is there no way to just display the content within the table without the extra click?

Thanks!

Josh

**Comment by slavarazum** [comment]
It opens with popup, because in general textareas has much content and it will be difficult to read it in table field directly.
