### ISSUE TITLE
Field content isn't updated when changing in code view

### ISSUE THREAD

**Issue by metalcamp** [froala/nova-froala-field#20]
Steps to reproduce: 
1. Go to resource which uses nova-froala-field
2. Click Create new <resource name>
3. Write content into Froala editor
4. Click save
5. Click edit on content that was just created
6. Go to Froala editor, click Code view
7. Change content (example: add `<p>test </p>`)
8. Click save

I would expect content to be changed, but it isn't. It remains the same, as it was on initial load (when clicked on edit, step 5). Not sure if this is intended behavior or it's a bug. 

Laravel version: 5.8.16
Nova version: 2.0.3
Nova Froala field version: 2.1.0

**Comment by slavarazum** [comment]
Thanks for your report!

But it isn't a bug actually. When you change something in raw code editor, you should switch back to normal mode for applying and reviewing your changes.
