### ISSUE TITLE
Embedly button not diplayed after upgrade to v3.0

### ISSUE THREAD

**Issue by techouse** [froala/nova-froala-field#23]
Hey! Great plugin, however after the recent upgrade from **v2.2.1** to **v3.0** the Embed.ly button is no longer displayed. I updated the `app/config/nova/froala-field.php` `toolbarButtons` array according to the [upgrading instructions](https://github.com/froala/nova-froala-field/blob/master/UPGRADING.md) but for some reason it's not displaying the Embed.ly button even though I have it in my config:

```php
'options' => [
        // 'key' => env('FROALA_KEY'),

        'iconsTemplate' => 'font_awesome_5',

        'tuiEnable' => true,

        'toolbarButtons' => [
            [
                'bold',
                'italic',
                'underline',
            ],
            [
                'formatOL',
                'formatUL',
            ],
            [
                'insertImage',
                'insertFile',
                'insertLink',
                'insertVideo',
                'embedly',
            ],
            [
                'html',
            ]
        ],
    ],
```

**Comment by slavarazum** [comment]
Thanks for reporting! Just tagged patch version [3.0.1](https://github.com/froala/nova-froala-field/releases/tag/3.0.1). Let me know if you will have any issues.

**Comment by techouse** [comment]
Thanks 🥰
