### ISSUE TITLE
Pulling through HTML tags onto page 

### ISSUE THREAD

**Issue by DCReddish97** [froala/nova-froala-field#24]
I've installed this to use on my page content management section within Laravel Nova.

In nova the actual field appear to work fine, but when I pull the inputted content through to the front end of my site it pulls through the html tags with it (e.g p tags, li tags, ul tags,  etc).

Am I missing something? 
Thanks

**Comment by slavarazum** [comment]
How do you inject your WYSIWYG content? Probably you have escaped it. You should display it unescaped with `{!! $model->content !!}}`
Check out documentation - https://laravel.com/docs/master/blade
