### ISSUE TITLE
Paragraphs within editor with no space between them

### ISSUE THREAD

**Issue by ilikourou** [froala/nova-froala-field#25]
Hello,

The html code of the content I have entered into Froala is the following:
```
<p>Hello</p>

<p>New paragraph</p>
```
However, within the editor there is no space between the paragraphs:
![Screenshot 2019-07-25 at 12 03 06](https://user-images.githubusercontent.com/9989667/61861292-35c65180-aed4-11e9-840e-7c461a44a157.png)

I have not made any changes to the default options, rather than adding
`'entities' => '&quot;&#39;&iexcl;&cent;&pound;&curren;&yen;&brvbar;',`

Thank you.

**Comment by slavarazum** [comment]
Hi!
By default, Nova resets margins for paragraphs to 0 and Froala hasn't it own styles for paragraphs.
If you want to declare your own styles for froala editor, you could create your own stylesheets:

**froala_styles_custom.css**
```css
.fr-view p {
    margin-bottom: 10px;
}
```

and include it to Nova:
https://nova.laravel.com/docs/1.0/customization/tools.html#assets
