### ISSUE TITLE
Events firing when editor loads

### ISSUE THREAD

**Issue by ilikourou** [froala/nova-froala-field#27]
Hello,

Following the instructions, I have created a .js file containing my event handlers:

```
window.froala = {
    events: {
        'image.inserted': ($img, response) => {
            console.log('inserted');
        }
    }
};
```

And then loaded this file in NovaServiceProvider::boot method:

 ```
Nova::serving(function (\Laravel\Nova\Events\ServingNova $event) {
    Nova::script('froala-event-handlers', public_path('js/froala-event-handlers.js'));
});
```

So far so good, when an image is inserted in the editor, the event is fired.
However, the event is also fired when the page firstly loads, without even giving focus to the editor. Is this normal behaviour?

**Comment by slavarazum** [comment]
I think yes, because images also inserts during field initialization. You can ask this question in official froala editor issue tracker - https://github.com/froala/wysiwyg-editor
