### ISSUE TITLE
Events firing when editor loads

### ISSUE THREAD

**Issue by ilikourou** [froala/nova-froala-field#28]
Hello,

I am using Froala in a **Laravel** application, utilising Nova and [nova-froala-field](https://github.com/froala/nova-froala-field) package.

Following the instructions of nova-froala-field, I have created a .js file containing my event handlers:

```
window.froala = {
    events: {
        'image.inserted': ($img, response) => {
            console.log('inserted');
        }
    }
};
```

And then loaded this file in NovaServiceProvider::boot method:

 ```
Nova::serving(function (\Laravel\Nova\Events\ServingNova $event) {
    Nova::script('froala-event-handlers', public_path('js/froala-event-handlers.js'));
});
```

So far so good, when an image is inserted in the editor, the event is fired.
However, the event is also "automatically" fired when the page firstly loads. The same happens for `image.loaded` and `image.error` events.
Is this the expected behaviour? 

Thank you,
Ilias

**Comment by casualuser** [comment]
@slavarazum 
Hi Slava,
It looks like this depends on integration and events handling. Please assist this customer with his question. If it is somehow related to Froala Editor itself then we will be happy to help.

**Comment by slavarazum** [comment]
@casualuser 
Hi Aleksei.
Already investigated this issue. Nothing special in Nova Froala Field integration. It native froala field behavior.
