### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by carloshc** [froala/nova-froala-field#3]
On ```config\nova\froala-field.php``` I tried:

````
    'options' => [
        'toolbarButtons' => [
            'bold',
            'italic',
            'underline',
            '|',
            'formatOL',
            'formatUL',
            '|',
            'insertImage',
            'insertFile',
            'insertLink',
            'insertVideo',
            '|',
            'html',
        ],
        'language' => 'pt_br',
    ],
````
and
`````
    'options' => [
        'toolbarButtons' => [
            'bold',
            'italic',
            'underline',
            '|',
            'formatOL',
            'formatUL',
            '|',
            'insertImage',
            'insertFile',
            'insertLink',
            'insertVideo',
            '|',
            'html',
        ],
    ],
    'language' => 'pt_br',

`````

, nothing happened.

Btw, is it possible to translate the **Show Content** and **Hide Content**?

**Comment by slavarazum** [comment]
It uses native Laravel localization services. You can find more information in [Nova documentation](https://nova.laravel.com/docs/1.0/customization/localization.html#overview)

**Comment by idragon81** [comment]
Yup, I did.
I think we have to import the translations the same way we are importing the plugins

**Comment by slavarazum** [comment]
Could you please clarify, in which way?
If you did these things it should works properly. I have tested it.

**Comment by zacksleo** [comment]
same issue. Any docs to setup language?

**Comment by FilNil** [comment]
Same issue here. I tried inserting the translations straight into my sv.json (since i have the swedish translation which works for the rest of nove). But the editor is still not translated.
Am i missing something here? I have read Novas translation docs and got it to work with nova. I have placed translation for the froala editor in the same file, but it does still not work.
