### ISSUE TITLE
Froala field disappear while typing

### ISSUE THREAD

**Issue by tharindu-abans** [froala/nova-froala-field#33]
**Laravel:** v5.8.33
**Laravel Nova:** v2.1.1
**Nova Froala Field:** v3.1.0
**Chrome:** v76.0.3809.132
**Firefox:** v68.0.2

I have integrated this into my project and it works most of the time.
But some times the field disappear while I'm typing, along with the content.
This happens randomly, but only when I'm typing on this field.
When this happens, I can see some Vue components being rendered onto the DOM.
I have verified this issue in both Chrome and Firefox as well as on other PCs.

![image](https://user-images.githubusercontent.com/48512374/63744592-6a576f80-c8bd-11e9-8ba9-8f08bafd6f79.png)
![image](https://user-images.githubusercontent.com/48512374/63744531-3da35800-c8bd-11e9-9844-a71194e9c512.png)

**Comment by slavarazum** [comment]
Need more details. Have you found why actually it disappears?

**Comment by tharindu-abans** [comment]
Actually, I was hoping you could tell me. It doesn't throw any errors or anything. But this only happens on my production server though.

I'm running:
**Ubuntu 18.04.3 LTS
PHP 7.3.8**

All I see is some Vue components being loaded into the DOM.
When it does that, the `textarea` that appear fails the required validation even when it is not empty.
![image](https://user-images.githubusercontent.com/48512374/63911213-2abc8f00-ca47-11e9-89d5-4329cff6f03a.png)

**Comment by slavarazum** [comment]
Can't reproduce behavior.
Feel free to reopen this issue with more details.

**Comment by gazben** [comment]
@tharindu-abans Same here for me. It just happens. Did you find a solution?

**Comment by gazben** [comment]
@slavarazum I was able to reproduce it. 
Version: 3.2.2

If you copy a text with a lot of lines and you delete the line endings. After ~8 line ending deletion the editor disappears.
