### ISSUE TITLE
Interger & Float error

### ISSUE THREAD

**Issue by kenkaigu** [froala/nova-froala-field#37]
![novaerror1](https://user-images.githubusercontent.com/31952302/66034466-f50d3900-e511-11e9-9a12-05edb83f454b.jpg)
That's the error message I am getting, immediately after installing the package. What could I be doing wrong?

**Comment by slavarazum** [comment]
Looks like you have configurated float value in froala config:
```php
config('nova.froala-field.upload_max_filesize')
```
or in php config:
```php
ini_get('upload_max_filesize')
```

It should be integer.

**Comment by slavarazum** [comment]
Feel free to reopen issue, if you will find bug in source code.
