### ISSUE TITLE
Issue with "/" key

### ISSUE THREAD

**Issue by hackerboydotcom** [froala/nova-froala-field#4]
I'm using MacOS 10.14, tested on Firefox and Chrome, both have this issue. When I try to type "/" or "?" on Froala editor, it'll automatically update the typing focus to the Nova search bar (at the top bar).

**Comment by slavarazum** [comment]
Thanks for reporting!
Fixed in [new release](https://github.com/froala/nova-froala-field/releases/tag/1.1.1).
