### ISSUE TITLE
Loading images using artisan serve

### ISSUE THREAD

**Issue by Sinnbeck** [froala/nova-froala-field#41]
As mentioned in here: https://github.com/froala/nova-froala-field/issues/18
There is an issue using getimagesize on local assets using url when running php artisan serve.

Just an idea. Check if the driver is local and if so use path instead

```
if (config('filesystems.disks')[$this->field->disk]['driver']) == 'local') {
        $path = $Storage->path($file);
    } else {
        $path = $Storage->url($file);
    }

    if (! app()->runningUnitTests() and ! @getimagesize($path)) {
        continue;
    }

**Comment by slavarazum** [comment]
Have you enabled `getimagesize` function for your PHP Interpreter?

**Comment by Sinnbeck** [comment]
Yes. It also works with either $Storage->path() for local files and $Storage->url() for external files. But calling @getimagesize('http://localhost:8000/some/local/file.jpg') will result in it loading forever. I have testet it on 2 different computers running ubuntu.

The suggested change above will ensure it works no matter what :)

**Comment by slavarazum** [comment]
Feel free to submit a PR with this solution :)

**Comment by slavarazum** [comment]
Please, provide a fully tested PR if you want to change some source code.
