### ISSUE TITLE
proc_open error when uploading an image

### ISSUE THREAD

**Issue by astalpaert** [froala/nova-froala-field#52]
Hi,

The editor is working, except image upload. I ran the migrations, but after uploading a file, I get an error:

Symfony\Component\Process\Exception\LogicException: The Process class relies on proc_open, which is not available on your PHP installation. in file /customers/c/e/1/jens/httpd.private/vendor/symfony/process/Process.php on line 143

#0 /customers/c/e/1/jens/httpd.private/vendor/symfony/process/Process.php(195): Symfony\Component\Process\Process->__construct(Array, NULL, NULL, NULL, 60)
#1 /customers/c/e/1/jens/httpd.private/vendor/spatie/image-optimizer/src/OptimizerChain.php(97): Symfony\Component\Process\Process::fromShellCommandline('"jpegoptim" -m8...')
#2 /customers/c/e/1/jens/httpd.private/vendor/spatie/image-optimizer/src/OptimizerChain.php(77): Spatie\ImageOptimizer\OptimizerChain->applyOptimizer(Object(Spatie\ImageOptimizer\Optimizers\Jpegoptim), Object(Spatie\ImageOptimizer\Image))
#3 /customers/c/e/1/jens/httpd.private/vendor/froala/nova-froala-field/src/Handlers/StorePendingAttachment.php(87): Spatie\ImageOptimizer\OptimizerChain->optimize('/customers/c/e/...')
#4 /customers/c/e/1/jens/httpd.private/vendor/froala/nova-froala-field/src/Handlers/StorePendingAttachment.php(53): Froala\NovaFroalaField\Handlers\StorePendingAttachment->imageOptimize('TgaIUKWHgfny57B...')
#5 [internal function]: Froala\NovaFroalaField\Handlers\StorePendingAttachment->__invoke(Object(Laravel\Nova\Http\Requests\NovaRequest))
#6 /customers/c/e/1/jens/httpd.private/vendor/froala/nova-froala-field/src/Http/Controllers/FroalaUploadController.php(25): call_user_func(Object(Froala\NovaFroalaField\Handlers\StorePendingAttachment), Object(Laravel\Nova\Http\Requests\NovaRequest))
#7 [internal function]: Froala\NovaFroalaField\Http\Controllers\FroalaUploadController->store(Object(Laravel\Nova\Http\Requests\NovaRequest), 'pages', 'content')
#8 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#9 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('store', Array)
#10 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Froala\NovaFroalaField\Http\Controllers\FroalaUploadController), 'store')
#11 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#12 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#13 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /customers/c/e/1/jens/httpd.private/nova/src/Http/Middleware/Authorize.php(18): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Nova\Http\Middleware\Authorize->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /customers/c/e/1/jens/httpd.private/nova/src/Http/Middleware/BootTools.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Nova\Http\Middleware\BootTools->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /customers/c/e/1/jens/httpd.private/nova/src/Http/Middleware/DispatchServingNovaEvent.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Nova\Http\Middleware\DispatchServingNovaEvent->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /customers/c/e/1/jens/httpd.private/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Nova\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#37 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#38 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#39 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#40 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#41 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#42 /customers/c/e/1/jens/httpd.private/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Nova\Http\Middleware\ServeNova->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /customers/c/e/1/jens/httpd.private/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#56 /customers/c/e/1/jens/httpd.private/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#57 /customers/c/e/1/jens/httpd.www/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#58 {main}

Thanks!

**Comment by slavarazum** [comment]
You should install php with `proc_open` function support
