### ISSUE TITLE
json field

### ISSUE THREAD

**Issue by yevhenkoriakin** [froala/nova-froala-field#57]
HI!
Not working with https://github.com/spatie/nova-translatable

error from console
`?field=translations_content_en 404 (Not Found)`

field
`$table->json('content');`

Thank you!

**Comment by shahabzebare** [comment]
same problem

**Comment by slavarazum** [comment]
Why do you store content in json column?

**Comment by shahabzebare** [comment]
Because of translation

**Comment by slavarazum** [comment]
Considering support of `spatie/nova-translatable` in future releases. Feel free to open a PR with json columns support.
