### ISSUE TITLE
Gallery Support question

### ISSUE THREAD

**Issue by henryavila** [froala/nova-froala-field#58]
Hi. This package looks great. I plan to buy it but I need to understand one think before.

About the upload capability, this editor support any kind of gallery? I mean, if I create a "post", and upload a image, if I need the same image in another "post", will I have to upload again the same image (having duplicated file in storage)? Or will I be able to select any of previously uploaded image?
In other words: The editor will be able to pick an already uploaded image?

I'm using `https://github.com/ebess/advanced-nova-media-library` the use the amazing `https://github.com/spatie/laravel-medialibrary to manage my library` package.  Is it compatible? If not, I need compatibility with some kind of Gallery, in My case the end user MUST be able to reuse an uploaded image.

**Comment by henryavila** [comment]
Hi. Any info about this?
Thanks!

**Comment by slavarazum** [comment]
When you press an image button, you can select "browse" tab.
Take a look into the playground - https://froala.com/wysiwyg-editor/

**Comment by henryavila** [comment]
Hi @slavarazum, thanks for replay.

I already saw the "browse" tab in the foraja docs.

My question is if in Nova field (this package) I have control of what content is displayed in the "browser tab". I say this because I run a multi tenant site, and one user, can`t see the images from other user (tenant)

**Comment by slavarazum** [comment]
Of course, you can customize attachment handlers - https://github.com/froala/nova-froala-field#customize-attachment-handlers

**Comment by henryavila** [comment]
Thanks @slavarazum!
