### ISSUE TITLE
Is a Commercial License Required?

### ISSUE THREAD

**Issue by waustin** [froala/nova-froala-field#60]
The code repo contains an MIT license, but the Froala website says the editor is commercial and costs money. https://froala.com/wysiwyg-editor/pricing?gclid=CjwKCAjw5vz2BRAtEiwAbcVIL83SDm8cge3744HqZgjvUpnYQYxmIeY46hjzEf71r_viAIluWPJT6RoCkV8QAvD_BwE

Do we need to purchase a license to use this Nova / Froala pacakge?

**Comment by slavarazum** [comment]
Nova Froala Field - it's adapter of Froala Editor for Laravel Nova and it's source code distributed under MIT license.
For commercial usage you should buy the license and pass it into config file - https://github.com/froala/nova-froala-field#license-key
