### ISSUE TITLE
Customize Attachment Handlers Throws error

### ISSUE THREAD

**Issue by Slgoetz** [froala/nova-froala-field#61]
When trying to implement a Customize Attachment Handler the same way the example is shown in the docs,  an error is thrown due to the lack of Field being passed in. However, you're unable to pass the Froala $field to the class from the Nova Resource.

**Do you have any recommendations for this?**

```
Froala::make('description')
    ->attach(new StorePendingMedia)
    ->detach(new DetachMedia)
    ->delete(new DeleteMedia)
     ->discard(new DiscardPendingMedia)
     ->images(new AttachedMediasList)
     ->options([
             'toolbarBottom'=>true,
             'height' => 400
     ]),
```

**Comment by slavarazum** [comment]
Need more details about error and your custom attachment handler implementation.

**Comment by slavarazum** [comment]
Feel free to reopen an issue with more details
