### ISSUE TITLE
JSON fields throws 404 error

### ISSUE THREAD

**Issue by ujackson** [froala/nova-froala-field#62]
In `FroalaUploadController` https://github.com/froala/nova-froala-field/blob/e4c5961662d29dcea95b0dab4e7ea25bf4dca2ad/src/Http/Controllers/FroalaUploadController.php#L21
`findFieldByAttribute` throws an 404 if the field is a JSON column like `data->content`

**Comment by godkinmo** [comment]
When I upload image  with json field...
the url in network request like this `/{resource}/attachments/content.en`

the suffix has `.{locale}`

I just update the `RouteServiceProvide` to handle this situation, hope it can help

```php
// ...

public function map()
{
    $this->registerRouteModelBindings();

    $this->mapApiRoutes();
    $this->mapWebRoutes();
}

protected function registerRouteModelBindings()
{
    Route::bind('field', function ($field) {
        if (
            Str::of($field)->endsWith('.en') ||
            Str::of($field)->endsWith('.zh-HK')
        ) {
            $column = Str::of($field)->replaceLast('.' . Str::of($field)->explode('.')->last(), '')->__toString();

            if ($column === 'popup_modal_content') {
                if (Route::currentRouteAction() === 'Froala\\NovaFroalaField\\Http\\Controllers\\FroalaUploadController@destroyPending') {
                    (new \Froala\NovaFroalaField\Models\PendingAttachment)->persistDraft(
                        request('draftId'),
                        \Froala\NovaFroalaField\Froala::make($column)->withFiles('public', 'settings'),
                        \App\Settings::where('key', $column)->first()
                    );
                }

                return $column;
            }

            return $field;
        }

        return $field;
    });
}
```

**Comment by slavarazum** [comment]
How do you define Froala field in Nova resource with JSON column?

**Comment by slavarazum** [comment]
Feel free to reopen an issue with more details

**Comment by FaZeRs** [comment]
@slavarazum If you use spatie translatable package then I get json field. I'm currenty having the same issue.
Using https://github.com/optimistdigital/nova-translatable

`Froala::make(__('Description'), 'description')->withFiles('public')->hideFromIndex()->translatable(),`
![Screenshot_43](https://user-images.githubusercontent.com/9529341/117196708-7d8b4400-adef-11eb-9c5b-9c3ac7b049c3.png)
