### ISSUE TITLE
How to make use of plugin options such as linkAlwaysBlank

### ISSUE THREAD

**Issue by FrazeColder** [froala/nova-froala-field#65]
Hi,

I am using the Frola editor and I would like to define some [options](https://froala.com/wysiwyg-editor/docs/options/#linkAlwaysBlank) such as `linkAlwaysBlank` or `linkAlwaysNoFollow`. The problem is I haven't found anything about it in the nova documentation. How can I do this?

Also, how can I add custom values to the `rel` attribute such as `noopener` as default?

Kind regards!

**Comment by slavarazum** [comment]
https://github.com/froala/nova-froala-field#customize-editor-options
