### ISSUE TITLE
Content saved in 'html' view are not persisting

### ISSUE THREAD

**Issue by jennicar** [froala/nova-froala-field#66]
We use this package for a laravel project. When editing content inside the froala editor, we oftentimes like to see it in code view to remove unwanted markup. It's unexpected behavior to have to exit code view in order to save the changes.

**Comment by slavarazum** [comment]
You can edit a raw html by switching to **Code View** mode. This functionality isn't specific to Nova Froala Field adoptation. If you will have some issues try to open it in general repository - https://github.com/froala/wysiwyg-editor
