### ISSUE TITLE
Working with S3

### ISSUE THREAD

**Issue by g0shed** [froala/nova-froala-field#7]
Trying to upload or list images on S3, I've set the ->withFiles('s3') but still nothing... aparently the path is not found

message: "The file "pa/xxx.jpg" does not exist",…

**Comment by g0shed** [comment]
aparently the problem is here:

`Froala\NovaFroalaField\Handlers\AttachedImagesList;`

specifically: 

```
if (! in_array(
                (new File($Storage->url($file)))->guessExtension(),
                ['jpeg', 'png', 'gif', 'bmp', 'svg']
            )) {
                continue;
            }
```

**Comment by slavarazum** [comment]
Could you please provide a server error? Has upload done successfully? Or just problem with list of  images?
Have you configured all of the s3 options?
```php
's3' => [
    'driver' => 's3',
    'key' => env('AWS_ACCESS_KEY_ID'),
    'secret' => env('AWS_SECRET_ACCESS_KEY'),
    'region' => env('AWS_DEFAULT_REGION'),
    'bucket' => env('AWS_BUCKET'),
    'url' => env('AWS_URL'),
],
```

**Comment by slavarazum** [comment]
Feel free to reopen an issue, if you still have a problem.
