### ISSUE TITLE
nova-froala-field:1 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by hackerboydotcom** [froala/nova-froala-field#70]
Tested on both: Mac/Windows Chrome/Firefox, got this issue.
From nova Froala Field, when you try to copy and paste, select all -> cut -> paste... I don't know how do it happen exactly. But once the error occur, the WYSIWYG editor will disappear, and a pure textarea will show instead, all the editing content will be lost. And below is what I get from console log (chrome).

nova-froala-field:1 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at m.offset (nova-froala-field:1)
    at Object.n [as getBoundingRect] (nova-froala-field:1)
    at Object.m [as positionCaret] (nova-froala-field:1)
    at Object.insert (nova-froala-field:1)
    at g (nova-froala-field:1)
    at p (nova-froala-field:1)
    at HTMLDivElement.d (nova-froala-field:1)

**Comment by hackerboydotcom** [comment]
Update: It seems to not happen in localhost but will happen in production when a license key isn't entered. Does it mean I'll need a license to avoid this error?

**Comment by slavarazum** [comment]
Try to ask it on the main repository - https://github.com/froala/wysiwyg-editor
It's not specific to Nova adaptation.
