### ISSUE TITLE
vendor:publish not working

### ISSUE THREAD

**Issue by FaridAghili** [froala/nova-froala-field#8]
Non of the vendor:publish commands (copy/pasted from readme) works.
All of them (config, migration, fonts) says Publishing complete, but no new file is added.
I'm on a Windows PC, so I don't think if it's related to dir permissions, as publishing the assets of other packages just works.

**Comment by FaridAghili** [comment]
I've did exactly as README said:

`php artisan vendor:publish --tag=config --provider=Froala\\NovaFroalaField\\FroalaFieldServiceProvider`

`php artisan vendor:publish --tag=migrations --provider=Froala\\NovaFroalaField\\FroalaFieldServiceProvider `

`php artisan vendor:publish --tag=froala-styles --provider=Froala\\NovaFroalaField\\FroalaFieldServiceProvider`

**Comment by slavarazum** [comment]
Looks like a problem with a windows shell. Try to use it like this:
```bash
php artisan vendor:publish --provider='Froala\NovaFroalaField\FroalaFieldServiceProvider'
```
or just run `php artisan vendor:publish` and chose necessary item from the list.
