### ISSUE TITLE
Froala key

### ISSUE THREAD

**Issue by chbbc** [froala/nova-froala-field#9]
Hi,
I purchased a license key, how activate it?

I put in ``config/nova/froala-field.php`` and doesn't work.

**Comment by slavarazum** [comment]
Hi. Try to add `key` option into `options`:
_config/nova/froala-field.php_
```php
// ...
'options' => [
    'key' => env('FROALA_KEY'),
    // ...
],
```

**Comment by slavarazum** [comment]
Will add this information into `readme`
